In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn import model_selection
from sklearn.metrics import confusion_matrix, classification_report

In [3]:
data = pd.read_csv('covid_early_stage_symptoms.csv')

In [4]:
data['gender'].replace({'male':1, 'female':0}, inplace=True)

In [5]:
data

gender  age_year  fever  cough  runny_nose  muscle_soreness  pneumonia  \
0          1        89      1      1           0                0          0   
1          1        68      1      0           0                0          0   
2          1        68      0      0           0                0          0   
3          1        68      1      1           0                0          0   
4          1        50      1      1           1                0          1   
...      ...       ...    ...    ...         ...              ...        ...   
6507       0        44      1      1           0                0          0   
6508       0        44      1      1           0                0          0   
6509       0        58      0      0           0                0          0   
6510       0        58      1      1           0                0          0   
6511       1        12      1      1           0                0          0   

      diarrhea  lung_infection  travel_history  isolation_treatment  \
0            0               0               1                    0   
1            0               0               0                    0   
2            0               0               1                    0   
3            0               0               1                    1   
4            0               0               1                    0   
...        ...             ...             ...                  ...   
6507         0               0               1                    0   
6508         0               0               0                    0   
6509         0               0               0                    0   
6510         0               0               0                    0   
6511         0               0               0                    1   

      SARS-CoV-2 Positive  
0                       0  
1                       0  
2                       0  
3                       1  
4                       1  
...                   ...  
6507                    1  
6508                    0  
6509                    0  
6510                    0  
6511                    0  

[6512 rows x 12 columns]

In [6]:
print(data.corr())

                       gender  age_year     fever     cough  runny_nose  \
gender               1.000000 -0.088342  0.008685 -0.006127    0.000157   
age_year            -0.088342  1.000000  0.046861  0.072975    0.014143   
fever                0.008685  0.046861  1.000000  0.763711    0.360032   
cough               -0.006127  0.072975  0.763711  1.000000    0.453879   
runny_nose           0.000157  0.014143  0.360032  0.453879    1.000000   
muscle_soreness      0.002713 -0.002193  0.070879  0.090664    0.024611   
pneumonia            0.006074  0.014113  0.340502  0.430910    0.936984   
diarrhea            -0.012800  0.037316  0.036549  0.047905   -0.000877   
lung_infection      -0.021905  0.043555  0.236403  0.311282    0.507186   
travel_history       0.010473 -0.085734 -0.324988 -0.427950   -0.197544   
isolation_treatment -0.025785  0.055691  0.230636  0.257287    0.144646   
SARS-CoV-2 Positive -0.007034  0.040054  0.434909  0.555225    0.477185   

                     mus

In [7]:
data.shape

(6512, 12)

In [8]:
print(data.groupby('SARS-CoV-2 Positive').size())

SARS-CoV-2 Positive
0    4940
1    1572
dtype: int64


In [9]:
pd.isnull(data).any()

gender                 False
age_year               False
fever                  False
cough                  False
runny_nose             False
muscle_soreness        False
pneumonia              False
diarrhea               False
lung_infection         False
travel_history         False
isolation_treatment    False
SARS-CoV-2 Positive    False
dtype: bool

In [53]:
print(data.corr())

                       gender  age_year     fever     cough  runny_nose  \
gender               1.000000 -0.088342  0.008685 -0.006127    0.000157   
age_year            -0.088342  1.000000  0.046861  0.072975    0.014143   
fever                0.008685  0.046861  1.000000  0.763711    0.360032   
cough               -0.006127  0.072975  0.763711  1.000000    0.453879   
runny_nose           0.000157  0.014143  0.360032  0.453879    1.000000   
muscle_soreness      0.002713 -0.002193  0.070879  0.090664    0.024611   
pneumonia            0.006074  0.014113  0.340502  0.430910    0.936984   
diarrhea            -0.012800  0.037316  0.036549  0.047905   -0.000877   
lung_infection      -0.021905  0.043555  0.236403  0.311282    0.507186   
travel_history       0.010473 -0.085734 -0.324988 -0.427950   -0.197544   
isolation_treatment -0.025785  0.055691  0.230636  0.257287    0.144646   
SARS-CoV-2 Positive -0.007034  0.040054  0.434909  0.555225    0.477185   

                     mus

In [45]:
data2 = data.drop(data.columns[9],axis = 1)
data2

gender  age_year  fever  cough  runny_nose  muscle_soreness  pneumonia  \
0          1        89      1      1           0                0          0   
1          1        68      1      0           0                0          0   
2          1        68      0      0           0                0          0   
3          1        68      1      1           0                0          0   
4          1        50      1      1           1                0          1   
...      ...       ...    ...    ...         ...              ...        ...   
6507       0        44      1      1           0                0          0   
6508       0        44      1      1           0                0          0   
6509       0        58      0      0           0                0          0   
6510       0        58      1      1           0                0          0   
6511       1        12      1      1           0                0          0   

      diarrhea  lung_infection  isolation_treatment  SARS-CoV-2 Positive  
0            0               0                    0                    0  
1            0               0                    0                    0  
2            0               0                    0                    0  
3            0               0                    1                    1  
4            0               0                    0                    1  
...        ...             ...                  ...                  ...  
6507         0               0                    0                    1  
6508         0               0                    0                    0  
6509         0               0                    0                    0  
6510         0               0                    0                    0  
6511         0               0                    1                    0  

[6512 rows x 11 columns]

Train Test Split Data - Logistic

In [66]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [67]:
X = data2.iloc[:,0:10].values
Y = data2.iloc[:,-1].values

In [68]:
validation_size = 0.20
seed = 7
X_train, X_validation, Y_train, Y_validation = model_selection.train_test_split(
    X, Y, test_size=validation_size, random_state=seed
)

In [69]:
print("Sebelum SMOTE , jumlah dari '1': {}".format(sum(Y_train == 1)))
print("Sebelum SMOTE , jumlah dari '0': {} \n".format(sum(Y_train == 0)))

Sebelum SMOTE , jumlah dari '1': 1267
Sebelum SMOTE , jumlah dari '0': 3942 



#Penambahan SMOTE

In [70]:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state = 2)
X_train_res, Y_train_res = sm.fit_resample(X_train, Y_train.ravel())
  
print('After OverSampling, the shape of train_X: {}'.format(X_train_res.shape))
print('After OverSampling, the shape of train_y: {} \n'.format(Y_train_res.shape))
  
print("After OverSampling, counts of label '1': {}".format(sum(Y_train_res == 1)))
print("After OverSampling, counts of label '0': {}".format(sum(Y_train_res == 0)))

After OverSampling, the shape of train_X: (7884, 10)
After OverSampling, the shape of train_y: (7884,) 

After OverSampling, counts of label '1': 3942
After OverSampling, counts of label '0': 3942


In [71]:
from sklearn.linear_model import LogisticRegression
logit = LogisticRegression()

#Tanpa SMOTE

In [78]:
logit.fit(X_train,Y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [79]:
print('accuracy :', logit.score(X_validation,Y_validation))

accuracy : 0.8971603990790483


In [80]:
logit.predict(X_validation)

array([0, 0, 0, ..., 1, 0, 0])

In [81]:
lr1 = LogisticRegression()
lr1.fit(X_train, Y_train.ravel())
predictions = lr1.predict(X_validation)

from sklearn.metrics import confusion_matrix, classification_report
# print classification report
print(classification_report(Y_validation, predictions))

              precision    recall  f1-score   support

           0       0.89      0.98      0.94       998
           1       0.91      0.62      0.74       305

    accuracy                           0.90      1303
   macro avg       0.90      0.80      0.84      1303
weighted avg       0.90      0.90      0.89      1303



/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


#Dengan SMOTE

In [82]:
logit.fit(X_train_res,Y_train_res)

LogisticRegression()

In [83]:
print('accuracy :', logit.score(X_validation,Y_validation))

accuracy : 0.8726016884113584


In [84]:
logit.predict(X_validation)

array([0, 1, 0, ..., 1, 0, 0])

In [85]:
lr1 = LogisticRegression()
lr1.fit(X_train_res, Y_train_res.ravel())
predictions = lr1.predict(X_validation)

# print classification report
print(classification_report(Y_validation, predictions))

              precision    recall  f1-score   support

           0       0.97      0.86      0.91       998
           1       0.67      0.91      0.77       305

    accuracy                           0.87      1303
   macro avg       0.82      0.89      0.84      1303
weighted avg       0.90      0.87      0.88      1303



Train Test Split Data - KNN

In [86]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

In [87]:
knn = KNeighborsClassifier()
svm = SVC()

In [88]:
knn.fit(X_train,Y_train)
print('accuracy :', knn.score(X_validation,Y_validation))

accuracy : 0.8626247122026094


In [89]:
knn.predict(X_validation)

array([0, 1, 0, ..., 0, 0, 0])

Train Test Split Data - Random Forest Classifier

In [90]:
rf = RandomForestClassifier()

# train the model
rf.fit(X_train_res, Y_train_res)
print('accuracy :', rf.score(X_validation,Y_validation))

# get predictions
predictions = rf.predict(X_validation)
print()
print(predictions)

print(classification_report(Y_validation, predictions))

accuracy : 0.861857252494244

[0 1 0 ... 1 0 0]
              precision    recall  f1-score   support

           0       0.94      0.88      0.91       998
           1       0.67      0.81      0.73       305

    accuracy                           0.86      1303
   macro avg       0.80      0.84      0.82      1303
weighted avg       0.88      0.86      0.87      1303



In [30]:
#rf_clf = RandomForestClassifier(criterion='entropy')   
#rf_clf.fit(X_train_res,Y_train_res)
#print('accuracy :', rf_clf.score(X_validation,Y_validation))
#print()

#from sklearn.metrics import confusion_matrix, classification_report
## print classification report
#print(rf_clf.classification_report(Y_validation, predictions))

Train Test Split Data - SVM

In [31]:
svm.fit(X_train,Y_train)
print('accuracy :', svm.score(X_validation,Y_validation))

accuracy : 0.8211818879508825


Evaluation-Logistic

In [32]:
mysample = np.array([1,89,1,1,0,0,0,0,0,1,0])
ex1 = mysample.reshape(1,-1)

In [33]:
ex1

array([[ 1, 89,  1,  1,  0,  0,  0,  0,  0,  1,  0]])

In [34]:
logit.predict(ex1)

array([0])

In [93]:
#melakukan testing pada model

#menginputkan paramter dengan urutan column pada dataset variabel x
mysample = [[1,23,1,0,1,1,1,1,0,0]]

#melakukan prediksi 
predicted = lr1.predict(mysample)
score = lr1.predict_proba(mysample)

if predicted == 1 :
    result = 'Positive'
    accuracy = str(score[0][1]*100)
else:
    result = 'Negative'
    accuracy = str(score[0][0]*100)
    
print('{0:.5}'.format(accuracy)+'%', 'kemungkinan anda', result, 'Covid-19')

94.30% kemungkinan anda Negative Covid-19


Evaluation-Random Forest

In [94]:
#melakukan testing pada model

#menginputkan paramter dengan urutan column pada dataset variabel x
mysample = [[1,23,1,0,1,1,1,1,0,0]]

#melakukan prediksi 
predicted = rf.predict(mysample)
score = rf.predict_proba(mysample)

if predicted == 1 :
    result = 'Positive'
    accuracy = str(score[0][1]*100)
else:
    result = 'Negative'
    accuracy = str(score[0][0]*100)
    
print('{0:.5}'.format(accuracy)+'%', 'kemungkinan anda', result, 'Covid-19')

57.50% kemungkinan anda Negative Covid-19


Evaluation-KNN

In [36]:
mysample = np.array([1,68,1,0,0,1,0,0,1,1,1])
ex2 = mysample.reshape(1,-1)

In [37]:
ex2

array([[ 1, 68,  1,  0,  0,  1,  0,  0,  1,  1,  1]])

In [38]:
knn.predict(ex2)

array([1])

In [39]:
#melakukan testing pada model

#menginputkan paramter dengan urutan column pada dataset variabel x
mysample = [[1,68,1,0,0,1,0,0,1,1,1]]

#melakukan prediksi 
predicted = knn.predict(mysample)
score = knn.predict_proba(mysample)

if predicted == 1 :
    result = 'Positive'
    accuracy = str(score[0][1]*100)
else:
    result = 'Negative'
    accuracy = str(score[0][0]*100)
    
print('{0:.5}'.format(accuracy)+'%', 'kemungkinan anda', result, 'Covid-19')

60.0% kemungkinan anda Positive Covid-19


Evaluation-SVM

In [40]:
mysample = np.array([1,68,1,0,0,1,0,0,1,1,1])
ex3 = mysample.reshape(1,-1)

In [41]:
ex3

array([[ 1, 68,  1,  0,  0,  1,  0,  0,  1,  1,  1]])

In [42]:
svm.predict(ex3)

array([0])

In [43]:
#Joblib

import joblib

joblib.dump(lr1,'log_smote_joblib')

['log_smote_joblib']